export const routes = {"sanctum.csrf-cookie": {url: () => `/sanctum/csrf-cookie`, method: "GET"},
"ignition.healthCheck": {url: () => `/_ignition/health-check`, method: "GET"},
"ignition.executeSolution": {url: () => `/_ignition/execute-solution`, method: "POST"},
"ignition.updateConfig": {url: () => `/_ignition/update-config`, method: "POST"},
"user.self": {url: () => `/api/user/self`, method: "GET"},
"user.recipients": {url: () => `/api/user/recipients`, method: "GET"},
"message.received": {url: () => `/api/message/messages/received`, method: "GET"},
"message.sent": {url: () => `/api/message/messages/sent`, method: "GET"},
"message.drafts": {url: () => `/api/message/messages/drafts`, method: "GET"},
"message.message": {url: (message: string|number) => `/api/message/message/${message}`, method: "GET"},
"message.store": {url: () => `/api/message/message`, method: "PUT"},
"message.update": {url: (message: string|number) => `/api/message/message/${message}`, method: "POST"},
"message.send": {url: (message: string|number) => `/api/message/message/${message}/send`, method: "POST"},
"message.delete": {url: (message: string|number) => `/api/message/message/${message}`, method: "DELETE"},
"auth.login": {url: () => `/api/auth/login`, method: "POST"},
"auth.register": {url: () => `/api/auth/register`, method: "POST"},
"route.routes": {url: () => `/api/route/routes`, method: "GET"},
"": {url: () => `//`, method: "GET"}}